# 修改TNAME: K2P 为您需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  # 强制开启现代 GitHub 的手动点击触发按钮
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install python3-docutils python-is-python3
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget

    - name: Clone source code
      run: |
        sudo rm -rf /opt/rt-n56u
        sudo mkdir -p /opt/rt-n56u
        sudo chown -R $USER:$USER /opt/rt-n56u
        
        # 纯净克隆，绝不读取外部环境变量
        git clone --depth=1 https://github.com /opt/rt-n56u
        
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/

    - name: Build Firmware
      env:
        TNAME: RM2100
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        
        ################################################################################################
        # 配置功能：不精简，启用原本的所有核心功能逻辑
        ################################################################################################
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n/CONFIG_FIRMWARE_INCLUDE_MENTOHUST=y/g' .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=y/g' .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y/g' .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n/CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y/g' .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n/CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=y/g' .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_WYY=n/CONFIG_FIRMWARE_INCLUDE_WYY=y/g' .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_V2RAY=n/CONFIG_FIRMWARE_INCLUDE_V2RAY=y/g' .config
        
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/

    - name : Upload packages
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images

